# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 786)
        MainWindow.setMinimumSize(QtCore.QSize(960, 786))
        MainWindow.setMaximumSize(QtCore.QSize(960, 786))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title_img = QtWidgets.QLabel(self.centralwidget)
        self.label_title_img.setGeometry(QtCore.QRect(0, 0, 960, 141))
        self.label_title_img.setObjectName("label_title_img")
        self.widget_quiry = QtWidgets.QWidget(self.centralwidget)
        self.widget_quiry.setGeometry(QtCore.QRect(0, 141, 960, 80))
        self.widget_quiry.setObjectName("widget_quiry")
        self.label_start = QtWidgets.QLabel(self.widget_quiry)
        self.label_start.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label_start.setObjectName("label_start")
        self.textEdit = QtWidgets.QTextEdit(self.widget_quiry)
        self.textEdit.setGeometry(QtCore.QRect(80, 20, 104, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_end = QtWidgets.QLabel(self.widget_quiry)
        self.label_end.setGeometry(QtCore.QRect(230, 30, 54, 12))
        self.label_end.setObjectName("label_end")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_quiry)
        self.textEdit_2.setGeometry(QtCore.QRect(300, 20, 104, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_quiry)
        self.textEdit_3.setGeometry(QtCore.QRect(540, 20, 104, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_serch = QtWidgets.QLabel(self.widget_quiry)
        self.label_serch.setGeometry(QtCore.QRect(460, 30, 54, 12))
        self.label_serch.setObjectName("label_serch")
        self.pushButton = QtWidgets.QPushButton(self.widget_quiry)
        self.pushButton.setGeometry(QtCore.QRect(760, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 230, 951, 551))
        self.widget.setObjectName("widget")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(15, 11, 921, 521))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "爬虫测试"))
        self.label_title_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_start.setText(_translate("MainWindow", "出发地："))
        self.label_end.setText(_translate("MainWindow", "到达地："))
        self.label_serch.setText(_translate("MainWindow", "时间："))
        self.pushButton.setText(_translate("MainWindow", "查询"))

def show_MainWindow():
    app = QtWidgets.QApplication(sys.argv)   #实例化类，作为GUI主程序入口
    MainWindow = QtWidgets.QMainWindow()     #创建MainWindow
    ui = Ui_MainWindow()                    #实例化UI类
    ui.setupUi(MainWindow)                  #设置窗体UI
    MainWindow.show()                       #显示窗体
    sys.exit(app.exec_())                   #当窗口创建完成，结束主循环进程
if __name__ == '__main__':
    show_MainWindow()