# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormDate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import pymysql
import sys
from SqlCheck.sql_out1 import *

try:
    db = pymysql.connect(host='47.112.243.226', user='test', password='qiyuan888.', database='user', port=13306)
except:
    sys.exit()
cursor = db.cursor()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 110, 791, 341))
        self.widget.setObjectName("widget")
        self.StartTime = QtWidgets.QTextEdit(self.widget)
        self.StartTime.setGeometry(QtCore.QRect(110, 140, 211, 41))
        self.StartTime.setObjectName("StartTime")
        self.EndTime = QtWidgets.QTextEdit(self.widget)
        self.EndTime.setGeometry(QtCore.QRect(520, 140, 211, 41))
        self.EndTime.setObjectName("EndTime")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 160, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(440, 160, 54, 12))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(350, 270, 91, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(300, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "开始时间："))
        self.label_2.setText(_translate("MainWindow", "结束时间："))
        self.pushButton.setText(_translate("MainWindow", "提交"))
        self.label_3.setText(_translate("MainWindow", "数据库日期查询时间选择"))
        self.pushButton.clicked.connect(self.get_date)
    def get_date(self):
        Start_time = self.StartTime.toPlainText()
        End_time = self.EndTime.toPlainText()
        try:
            Rsql = SqlOut(Starttime=Start_time, Endtime=End_time)
            Rsql.Zhuce()
            workbook.save('%r导出文件.xls' % today)
            QtWidgets.QMessageBox.about(self,'提示','数据导出成功')
            cursor.close()
            db.close()
        except:
            cursor.close()
            db.close()
            QtWidgets.QMessageBox.Warning(self,'错误','数据导出失败')



def show_Window():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    show_Window()
