# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import Qt
import sys
import Request

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(775, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.label_img.setStyleSheet("background-color: rgb(255, 213, 214);")
        self.label_img.setObjectName("label_img")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 80, 771, 51))
        self.widget.setObjectName("widget")
        self.label_style = QtWidgets.QLabel(self.widget)
        self.label_style.setGeometry(QtCore.QRect(80, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_style.setFont(font)
        self.label_style.setObjectName("label_style")
        self.textEdit_style = QtWidgets.QTextEdit(self.widget)
        self.textEdit_style.setGeometry(QtCore.QRect(130, 10, 121, 31))
        self.textEdit_style.setObjectName("textEdit_style")
        self.label_time = QtWidgets.QLabel(self.widget)
        self.label_time.setGeometry(QtCore.QRect(320, 20, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.dateEdit_time = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_time.setGeometry(QtCore.QRect(370, 10, 131, 31))
        self.dateEdit_time.setObjectName("dateEdit_time")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(620, 16, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 140, 771, 451))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 761, 441))
        self.textBrowser.setObjectName("textBrowser")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)


    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "豆瓣电影"))
        self.label_img.setText(_translate("mainWindow", ""))
        self.label_style.setText(_translate("mainWindow", "类型："))
        self.label_time.setText(_translate("mainWindow", "时间:"))
        self.pushButton.setText(_translate("mainWindow", "查询"))

        self.pushButton.clicked.connect(self.on_click)

    def on_click(self,mainWindow):
        _translate = QtCore.QCoreApplication.translate
        the_style = self.textEdit_style.toPlainText()
        the_time = self.dateEdit_time.text()
        self.textBrowser.setText(_translate('mainWindow','%r')%Request.titles_list)

def show_MainWindow():
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    show_MainWindow()

